# Based on https://github.com/actions/starter-workflows/blob/main/pages/astro.yml
name: Deploy Website and Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  WEBSITE_PATH: "website"
  DOCS_PATH: "docs"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Build website from gazebosim-web-frontend
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: gazebo-web/gazebosim-web-frontend
          ref: support_github_pages
          path: ${{ env.WEBSITE_PATH }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ env.WEBSITE_PATH }}/package-lock.json
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Website dependencies
        run: npm ci
        working-directory: ${{ env.WEBSITE_PATH }}
      - name: Build Website
        run: npm run build -- --base-href "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.WEBSITE_PATH }}


      # Build Docs
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.DOCS_PATH }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install Docs dependencies
        run: pip install -r requirements.txt
        working-directory: ${{ env.DOCS_PATH }}
      - name: Build Docs
        run: python build_multiversion.py --pointers --libs --output_dir ${{ github.workspace }}/${{ env.WEBSITE_PATH }}/dist 
        env:
          GZ_DEPLOY_URL: "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.DOCS_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.WEBSITE_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
