name: Deploy API Docs

on:
  pull_request:
  schedule:
   # UTC timezone
   - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build_api_docs:
    name: 'Build API Docs (${{ matrix.gazebo_distribution }})'
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.ubuntu_distribution }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - ubuntu_distribution: ubuntu:focal
          #   gazebo_distribution: citadel
          #
          # - ubuntu_distribution: ubuntu:focal
          #   gazebo_distribution: fortress

          # - ubuntu_distribution: ubuntu:focal
          #   gazebo_distribution: garden

          - ubuntu_distribution: jammy
            gazebo_distribution: harmonic
    steps:
      - uses: ros-tooling/setup-ros@v0.7
      - name: 'Set up Gazebo'
        uses: gazebo-tooling/setup-gazebo@1f55cec330de851fa373f1ade8ac6b7ddfe6f013
        with:
          required-gazebo-distributions: ${{ matrix.gazebo_distribution }}
      - name: 'Add Doxygen'
        run: sudo apt-get install -y doxygen
      - name: 'Build Docs'
        run: |
          mkdir -p ws/src
          cd ws/src
          vcs import --input https://raw.githubusercontent.com/gazebo-tooling/gazebodistro/master/collection-${{ matrix.gazebo_distribution}}.yaml
          rm -rf sdformat
          sudo apt-get -y install $(sort -u $(find . -iname 'packages-'${{ matrix.ubuntu_distribution}}'.apt' -o -iname 'packages.apt' | grep -v '/\.git/') | tr '\n' ' ')
          cd ..
          colcon build --merge-install --event-handlers console_cohesion+ --cmake-args -DBUILD_DOCS=ON --cmake-target doc
