name: Deploy API Docs

on:
  pull_request:
  schedule:
   # UTC timezone
   - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build_api_docs:
    name: 'Build API Docs (${{ matrix.gazebo_distribution }})'
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.docker_image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - docker_image: ubuntu:focal
          #   gazebo_distribution: citadel
          #
          # - docker_image: ubuntu:focal
          #   gazebo_distribution: fortress

          # - docker_image: ubuntu:focal
          #   gazebo_distribution: garden

          - docker_image: ubuntu:jammy
            gazebo_distribution: harmonic
    steps:
      - uses: ros-tooling/setup-ros@v0.7
      - name: 'Set up Gazebo'
        uses: gazebo-tooling/setup-gazebo@1f55cec330de851fa373f1ade8ac6b7ddfe6f013
        with:
          required-gazebo-distributions: ${{ matrix.gazebo_distribution }}
      - name: 'Add Doxygen'
        run: sudo apt-get install -y doxygen
      - name: 'Install Gazebo recommended packages'
        run: |
          sudo apt-get remove -y gz-${{ matrix.gazebo_distribution}}
          sudo apt-get install -y gz-${{ matrix.gazebo_distribution}}
      - name: 'Build Docs'
        run: |
          mkdir -p ws/src
          cd ws/src
          vcs import --input https://raw.githubusercontent.com/gazebo-tooling/gazebodistro/master/collection-${{ matrix.gazebo_distribution}}.yaml
          cd ..
          colcon build --event-handlers console_cohesion+ --cmake-args -DBUILD_DOCS=ON --cmake-target doc --packages-skip-regex sdformat
